context:
  version: "17.10.4"

package:
  name: release-please
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-please/-/release-please-${{ version }}.tgz
  sha256: 4474b79b7ffd67e3c026be97f0486efb1a1742238fee7289d77a4b98f7776f11

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-please --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: generate release PRs based on the conventionalcommits.org spec
  homepage: https://github.com/googleapis/release-please
  repository: https://github.com/googleapis/release-please

extra:
  recipe-maintainers:
    - danielnachun
