context:
  version: "17.10.3"

package:
  name: release-please
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-please/-/release-please-${{ version }}.tgz
  sha256: 93aa912aefb737f3335462126fd621d3b179d0e172b4b6da374b46d2aefa58e8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-please --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: generate release PRs based on the conventionalcommits.org spec
  homepage: https://github.com/googleapis/release-please
  repository: https://github.com/googleapis/release-please

extra:
  recipe-maintainers:
    - danielnachun
