context:
  version: "17.11.0"

package:
  name: release-please
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-please/-/release-please-${{ version }}.tgz
  sha256: 903fd0d8e1f23cf9e34f8c0f75e7d0bc485e8e63126d940f7fa5254a744c0100

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-please --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: generate release PRs based on the conventionalcommits.org spec
  homepage: https://github.com/googleapis/release-please
  repository: https://github.com/googleapis/release-please

extra:
  recipe-maintainers:
    - danielnachun
