context:
  version: "17.1.2"

package:
  name: release-please
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-please/-/release-please-${{ version }}.tgz
  sha256: 07ad4cf4db7ab34a122c92042597b7a474b75e00b25bf6862ed6c4fa6ac1d9af

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-please --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: generate release PRs based on the conventionalcommits.org spec
  homepage: https://github.com/googleapis/release-please
  repository: https://github.com/googleapis/release-please

extra:
  recipe-maintainers:
    - danielnachun
