context:
  version: "16.16.0"

package:
  name: release-please
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-please/-/release-please-${{ version }}.tgz
  sha256: 189a0d30059275d67060c06040979dfea5976d799c912a6859d7d71bd82b665d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-please --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: generate release PRs based on the conventionalcommits.org spec
  homepage: https://github.com/googleapis/release-please
  repository: https://github.com/googleapis/release-please

extra:
  recipe-maintainers:
    - danielnachun
